-- modelgate initial schema. Generated by `prisma migrate dev --name init`.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE "documents" (
    "id" UUID NOT NULL,
    "sourceUri" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "sha256" TEXT NOT NULL,
    "corpusTag" TEXT NOT NULL,
    "ingestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "chunkCount" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "documents_sourceUri_key" ON "documents"("sourceUri");
CREATE INDEX "documents_corpusTag_idx" ON "documents"("corpusTag");

CREATE TABLE "chunks" (
    "id" UUID NOT NULL,
    "documentId" UUID NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "content" TEXT NOT NULL,
    "tokenCount" INTEGER NOT NULL,
    "embedding" vector(1024),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "chunks_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "chunks_documentId_ordinal_key" ON "chunks"("documentId", "ordinal");

-- HNSW index for cosine distance. Built after ingest for a cold corpus; for
-- incremental ingest pgvector maintains it online.
CREATE INDEX "chunks_embedding_hnsw" ON "chunks"
    USING hnsw ("embedding" vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE TABLE "semantic_cache" (
    "id" UUID NOT NULL,
    "question" TEXT NOT NULL,
    "questionEmbedding" vector(1024) NOT NULL,
    "answer" TEXT NOT NULL,
    "citations" JSONB NOT NULL,
    "model" TEXT NOT NULL,
    "corpusVersion" TEXT NOT NULL,
    "hits" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "semantic_cache_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "semantic_cache_corpusVersion_idx" ON "semantic_cache"("corpusVersion");
CREATE INDEX "semantic_cache_expiresAt_idx" ON "semantic_cache"("expiresAt");
CREATE INDEX "semantic_cache_embedding_hnsw" ON "semantic_cache"
    USING hnsw ("questionEmbedding" vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE TABLE "usage_events" (
    "id" UUID NOT NULL,
    "requestId" TEXT NOT NULL,
    "route" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "requestedModel" TEXT NOT NULL,
    "fellBack" BOOLEAN NOT NULL DEFAULT false,
    "cacheOutcome" TEXT NOT NULL,
    "inputTokens" INTEGER NOT NULL DEFAULT 0,
    "outputTokens" INTEGER NOT NULL DEFAULT 0,
    "embeddingTokens" INTEGER NOT NULL DEFAULT 0,
    "retrievalMs" INTEGER NOT NULL DEFAULT 0,
    "modelMs" INTEGER NOT NULL DEFAULT 0,
    "totalMs" INTEGER NOT NULL DEFAULT 0,
    "costUsd" DECIMAL(12,8) NOT NULL DEFAULT 0,
    "refused" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "usage_events_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "usage_events_createdAt_idx" ON "usage_events"("createdAt");
CREATE INDEX "usage_events_model_idx" ON "usage_events"("model");

ALTER TABLE "chunks" ADD CONSTRAINT "chunks_documentId_fkey"
    FOREIGN KEY ("documentId") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE CASCADE;
