apiVersion: 1

datasources:
  - name: modelgate-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: modelgate
    user: modelgate
    secureJsonData:
      password: modelgate
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
